[package]
name = "stardust"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
iced = { version = "0.13.1", features = ["tokio", "wgpu"] }
num-traits = "0.2.19"
rust_decimal = { version =  "1.37.2", features = ["macros"] }
